Repository stride3d/stride, pull requests merged in 2024-04, with the labels that each got.

#2163 [Asset] Unified 3D asset importer (on behalf of Noa7/Noah7071)
  build/Stride.sln
  sources/editor/Stride.Assets.Presentation/Templates/ModelAssetTemplateWindow.xaml
  sources/editor/Stride.Assets.Presentation/Templates/ModelAssetTemplateWindow.xaml.cs
  sources/editor/Stride.Assets.Presentation/Templates/ModelFromFileTemplateGenerator.cs
  sources/engine/Stride.Assets.Models/FbxAssetImporter.cs
  sources/engine/Stride.Assets.Models/ImportFbxCommand.cs
  sources/engine/Stride.Assets.Models/ImportModelCommand.Animation.cs
  sources/engine/Stride.Assets.Models/ImportModelCommand.SkeletonMapping.cs
  sources/engine/Stride.Assets.Models/ImportModelCommand.cs
  sources/engine/Stride.Assets.Models/ImportThreeDCommand.cs
  sources/engine/Stride.Assets.Models/ModelAssetImporter.cs
  sources/engine/Stride.Assets.Models/Stride.Assets.Models.csproj
  sources/engine/Stride.Assets.Models/ThreeDAssetImporter.cs
  sources/tools/Stride.Importer.3D/Material/Flags.cs
  sources/tools/Stride.Importer.3D/Material/MappingMode.cs
  sources/tools/Stride.Importer.3D/Material/MaterialStack.cs
  sources/tools/Stride.Importer.3D/Material/Materials.cs
  sources/tools/Stride.Importer.3D/Material/Operation.cs
  sources/tools/Stride.Importer.3D/Material/StackColor.cs
  sources/tools/Stride.Importer.3D/Material/StackElement.cs
  sources/tools/Stride.Importer.3D/Material/StackElementType.cs
  sources/tools/Stride.Importer.3D/Material/StackOperation.cs
  sources/tools/Stride.Importer.3D/Material/StackTexture.cs
  sources/tools/Stride.Importer.3D/MeshConverter.cs
  sources/tools/Stride.Importer.3D/Stride.Importer.3D.csproj
  sources/tools/Stride.Importer.3D/Utils.cs
  sources/tools/Stride.Importer.FBX/AnimationConverter.h
  sources/tools/Stride.Importer.FBX/AssemblyInfo.h
  sources/tools/Stride.Importer.FBX/ImporterUtils.h
  sources/tools/Stride.Importer.FBX/MeshConverter.cpp
  sources/tools/Stride.Importer.FBX/SceneMapping.h
  sources/tools/Stride.Importer.FBX/StreamReader.cpp
  sources/tools/Stride.Importer.FBX/StreamReader.h
  sources/tools/Stride.Importer.FBX/Stride.Importer.FBX.vcxproj
  sources/tools/Stride.Importer.FBX/Stride.Importer.FBX.vcxproj.filters
  sources/tools/Stride.Importer.FBX/UtilityFunctions.cpp
  sources/tools/Stride.Importer.FBX/UtilityFunctions.h
  sources/tools/Stride.Importer.FBX/stdafx.cpp
  sources/tools/Stride.Importer.FBX/stdafx.h
Labels: area-Asset

#2170 fix: Xml Comments - Update 4
  sources/assets/Stride.Core.Assets/Analysis/AssetBaseAnalysis.cs
  sources/assets/Stride.Core.Assets/Compiler/AssetCompilerResult.cs
  sources/assets/Stride.Core.Assets/PackageSessionResult.cs
  sources/assets/Stride.Core.Assets/Serializers/IdentifiableAssetPartReference.cs
  sources/assets/Stride.Core.Assets/UnloadableObjectRemover.cs
  sources/core/Stride.Core.MicroThreading/Channel.cs
  sources/core/Stride.Core.Serialization/Storage/IOdbBackend.cs
  sources/core/Stride.Core.Serialization/Storage/ObjectDatabase.cs
  sources/core/Stride.Core/Collections/FastTrackingCollectionChangedEventArgs.cs
  sources/core/Stride.Core/Collections/TrackingCollectionChangedEventArgs.cs
  sources/core/Stride.Core/Diagnostics/ExceptionInfo.cs
  sources/core/Stride.Core/Diagnostics/ProfilingState.cs
  sources/core/Stride.Core/Native/NativeLibraryHelper.cs
  sources/engine/Stride.Audio/AudioEngine.cs
  sources/engine/Stride.Audio/IPlayableSound.cs
  sources/engine/Stride.Engine/Animations/AnimationCurve.cs
  sources/engine/Stride.Engine/Engine/Entity.cs
  sources/engine/Stride.Engine/Engine/SceneInstance.cs
  sources/engine/Stride.Engine/Rendering/CameraComponentRendererExtensions.cs
  sources/engine/Stride.Engine/Rendering/Compositing/GraphicsCompositor.cs
  sources/engine/Stride.Engine/Rendering/Compositing/SceneCameraSlotCollection.cs
  sources/engine/Stride.Games/SDL/GameFormSDL.cs
  sources/engine/Stride.Graphics/AppContextType.cs
  sources/engine/Stride.Graphics/Blend.cs
  sources/engine/Stride.Graphics/BufferFlags.cs
  sources/engine/Stride.Graphics/CubeMapFace.cs
  sources/engine/Stride.Graphics/CullMode.cs
  sources/engine/Stride.Graphics/GeometricPrimitives/GeometricPrimitive.cs
  sources/engine/Stride.Graphics/GraphicsPresenter.cs
  sources/engine/Stride.Graphics/MapMode.cs
  sources/engine/Stride.Graphics/MappedResource.cs
  sources/engine/Stride.Graphics/PrimitiveQuad.cs
  sources/engine/Stride.Graphics/SDL/Window.cs
  sources/engine/Stride.Graphics/SpriteExtensions.cs
  sources/engine/Stride.Graphics/TextureDescription.cs
  sources/engine/Stride.Graphics/VertexElement.cs
  sources/engine/Stride.Input/PointerDeviceState.cs
  sources/engine/Stride.Rendering/Rendering/Compositing/SceneRendererBase.cs
  sources/engine/Stride.Rendering/Rendering/GraphicsRendererCollection.cs
  sources/engine/Stride.Rendering/Rendering/GraphicsRendererCollectionBase.cs
  sources/engine/Stride.Rendering/Rendering/Images/ImageEffect.cs
  sources/engine/Stride.Rendering/Rendering/Images/ImageEffectShader.cs
  sources/engine/Stride.Rendering/Rendering/Lights/ForwardLightingRenderFeature.cs
  sources/engine/Stride.Rendering/Rendering/Lights/LightDirectionalShadowMap.cs
  sources/engine/Stride.Rendering/Rendering/Lights/LightSkybox.cs
  sources/engine/Stride.Rendering/Rendering/RenderEffect.cs
  sources/engine/Stride.Rendering/Rendering/RendererCoreBase.cs
Labels: area-Doc

#2142 Adjust ToolLocator for all platforms
  sources/core/Stride.Core.Design/IO/UPath.cs
  sources/engine/Stride.Assets/Media/SoundAssetCompiler.cs
  sources/engine/Stride.Assets/Media/VideoAssetCompiler.cs
  sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontImporter.cs
  sources/engine/Stride.Assets/ToolLocator.cs
Labels: enhancement, area-Build, area-Asset

#2218 NETFramework requirement is not needed anymore
  sources/launcher/Stride.Launcher/Launcher.cs
  sources/launcher/Stride.Launcher/PrerequisitesValidator.cs
Labels: area-Build

#2225 fix: PublishSingleFile Launch Crash
  sources/core/Stride.Core/PlatformFolders.cs
Labels: area-Build
