Repository stride3d/stride, pull requests merged in 2024-03, with the labels that each got.

#2137 feat: Release.yml added for PR categorisation
  .github/release.yml
Labels: area-Build

#2181 fix: File GraphicsResourceMap.cs without references removed
  sources/engine/Stride.Graphics/GraphicsResourceMap.cs
Labels: engineering

#2187 feat: Update samples/template to top-level statements
  samples/Audio/SimpleAudio/SimpleAudio.Windows/SimpleAudioApp.cs
  samples/Games/JumpyJet/JumpyJet.Windows/JumpyJetApp.cs
  samples/Games/SpaceEscape/SpaceEscape.Windows/SpaceEscapeApp.cs
  samples/Graphics/AnimatedModel/AnimatedModel.Windows/AnimatedModelApp.cs
  samples/Graphics/CustomEffect/CustomEffect.Windows/CustomEffectApp.cs
  samples/Graphics/MaterialShader/MaterialShader.Windows/MaterialShaderApp.cs
  samples/Graphics/SpriteFonts/SpriteFonts.Windows/SpriteFontsApp.cs
  samples/Graphics/SpriteStudioDemo/SpriteStudioDemo.Windows/SpriteStudioDemoApp.cs
  samples/Input/GravitySensor/GravitySensor.Windows/GravitySensorApp.cs
  samples/Input/TouchInputs/TouchInputs.Windows/TouchInputsApp.cs
  samples/Particles/ParticlesSample/ParticlesSample.Windows/ParticlesSampleApp.cs
  samples/Physics/PhysicsSample/PhysicsSample.Windows/PhysicsSampleApp.cs
  samples/StrideSamples.userprefs
  samples/Templates/FirstPersonShooter/FirstPersonShooter/FirstPersonShooter.Windows/FirstPersonShooterApp.cs
  samples/Templates/ThirdPersonPlatformer/ThirdPersonPlatformer/ThirdPersonPlatformer.Windows/ThirdPersonPlatformerApp.cs
  samples/Templates/TopDownRPG/TopDownRPG/TopDownRPG.Windows/TopDownRPGApp.cs
  samples/Templates/VRSandbox/VRSandbox/VRSandbox.Windows/VRSandboxApp.cs
  samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Windows/CSharpBeginnerApp.cs
  samples/Tutorials/CSharpIntermediate/CSharpIntermediate/CSharpIntermediate.Windows/CSharpIntermediateApp.cs
  samples/UI/GameMenu/GameMenu.Windows/GameMenuApp.cs
  samples/UI/UIElementLink/UIElementLink.Windows/UIElementLinkApp.cs
  samples/UI/UIParticles/UIParticles.Windows/UIParticlesApp.cs
  sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Linux/$PackageGameNameShort$App.cs.t4
  sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Windows/$PackageGameNameShort$App.cs.t4
  sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.macOS/$PackageGameNameShort$App.cs.t4
  sources/engine/Stride.Input.Tests/AdvancedInputTest.cs
  sources/engine/Stride.Input.Tests/TestInputEvents.cs
Labels: area-Samples

#2195 [Presentation] Fix issue with binding quantum nodes when associated name is not found
  sources/editor/Stride.Core.Assets.Editor/Module.cs
  sources/presentation/Stride.Core.Presentation.Quantum/ViewModels/NodeViewModel.cs
Labels: bug
