Repository stride3d/stride, pull requests merged in 2024-06, with the labels that each got.

#2274 fix: fullscreen and game exit windowing crashes
  sources/engine/Stride.Games/Desktop/GameForm.cs
  sources/engine/Stride.Games/Desktop/GameWindowWinforms.cs
  sources/engine/Stride.Games/GameBase.cs
  sources/engine/Stride.Games/GameContext.cs
  sources/engine/Stride.Games/GameWindow.cs
  sources/engine/Stride.Games/GraphicsDeviceManager.cs
  sources/engine/Stride.Graphics/ResumeManager.cs
Labels: area-Graphics

#2315 fix: Rollback one of the TryAdd introduced through #2299, VS Package is still on net472
  sources/core/Stride.Core.Yaml/Schemas/SchemaBase.cs
Labels: area-Build

#2332 refactor: Make FastList Obsolete
  sources/core/Stride.Core/Collections/FastList.cs
Labels: area-Core

#2291 fix: AssImp orientation, imported material color fallback, and set default animation preview model
  sources/engine/Stride.Assets.Models/ModelAssetImporter.cs
  sources/tools/Stride.Importer.3D/MeshConverter.cs
  sources/tools/Stride.Importer.3D/aiPostProcessSteps.cs
Labels: area-Asset

#2321 style: Set initial visibility for ModelComponent gizmos off
  sources/editor/Stride.Assets.Presentation/SceneEditor/PackageSceneSettings.cs
Labels: area-GameStudio

#2331 feat: FlexibleProcessing as alternative to EntityComponentProcessor for lightweight, abstract and typesafe processing in idiomatic c#
  sources/engine/Stride.Engine.Tests/TestEntityManager.cs
  sources/engine/Stride.Engine/Engine/EntityManager.cs
  sources/engine/Stride.Engine/Engine/FlexibleProcessing/IComponent.cs
  sources/engine/Stride.Engine/Engine/FlexibleProcessing/IDrawProcessor.cs
  sources/engine/Stride.Engine/Engine/FlexibleProcessing/IProcessorBase.cs
  sources/engine/Stride.Engine/Engine/FlexibleProcessing/IUpdateProcessor.cs
  sources/engine/Stride.Engine/Engine/FlexibleProcessing/ProcessorManager.cs
Labels: area-Core

#2362 fix: importing effects to the EffectCompileLog
  sources/editor/Stride.Assets.Presentation/EffectCompilerServerSession.cs
Labels: area-Graphics
