Repository stride3d/stride, pull requests merged in 2024-12, with the labels that each got.

#2537 [Build] Update NuGet.* packages to version 6.12.1
  sources/Directory.Packages.props
Labels: area-Build

#2534 fix: Bepu, ensure users require an explicit reference to bepu before being able to use related components and assets
  build/Stride.sln
  sources/assets/Stride.Core.Assets.CompilerApp/Stride.Core.Assets.CompilerApp.csproj
  sources/assets/Stride.Core.Assets/StridePackagesToSkipUpgrade.cs
  sources/editor/Stride.Assets.Presentation/Stride.Assets.Presentation.sdpkg
  sources/editor/Stride.Assets.Presentation/StrideDefaultAssetsPlugin.cs
  sources/editor/Stride.Assets.Presentation/Templates/HullAssetFactoryTemplateGenerator.cs
  sources/editor/Stride.Editor/Stride.Editor.csproj
  sources/editor/Stride.GameStudio/Debugging/AssemblyRecompiler.cs
  sources/editor/Stride.GameStudio/Stride.GameStudio.csproj
  sources/engine/Stride.Assets/AllAssets.Display.cs
  sources/engine/Stride.Assets/BepuPhysics/HullAsset.cs
  sources/engine/Stride.Assets/BepuPhysics/HullAssetFactory.cs
  sources/engine/Stride.Assets/Stride.Assets.csproj
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Assets/HullAsset.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/CharacterComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/AngularAxisGearMotorConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/AngularAxisMotorConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/AngularHingeConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/AngularMotorConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/AngularServoConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/AngularSwivelHingeConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/AreaConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/BallSocketConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/BallSocketMotorConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/BallSocketServoConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/CenterDistanceConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/CenterDistanceLimitConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/DistanceLimitConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/DistanceServoConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/HingeConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/LinearAxisLimitConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/LinearAxisMotorConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/LinearAxisServoConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/OneBodyAngularMotorConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/OneBodyAngularServoConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/OneBodyLinearMotorConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/OneBodyLinearServoConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/PointOnLineServoConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/SwingLimitConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/SwivelHingeConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/TwistLimitConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/TwistMotorConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/TwistServoConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/VolumeConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/WeldConstraintComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/_ConstraintComponentBase.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Definitions/ServicesHelper.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/StaticComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Stride.BepuPhysics.csproj
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Stride.BepuPhysics.sdpkg
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Systems/ConstraintProcessor.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Templates/Assets/.sdtpl/ColliderHull.png
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Templates/Assets/Bepu/HullAsset.sdtpl
Labels: area-Physics

#2535 feat: ExecutionMode control for Flexible Processing
  sources/engine/Stride.Engine/Engine/EntityManager.cs
  sources/engine/Stride.Engine/Engine/FlexibleProcessing/IProcessorBase.cs
  sources/engine/Stride.Engine/Engine/FlexibleProcessing/ProcessorManager.cs
Labels: area-Core

#2473 docs: README.md update - Consistency updates
  CODE_OF_CONDUCT.md
  README.md
Labels: area-Doc

#2546 fix: Replace Xenko logo with Stride logo in MaterialModel.fbx
  samples/Templates/Packs/MaterialPackage/Resources/Models/MaterialModel.fbx
Labels: area-Asset

#2548 chore: Update ServiceWire package to version 5.6.0
  sources/Directory.Packages.props
Labels: area-Build

#2563 [Android] Fix invalid configuration in Android solution file.
  build/Stride.Android.sln
Labels: area-Build

#2571 feat: Bepu, Allow user to set thread count
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BepuSimulation.cs
Labels: area-Physics

#2582 feat: added outline support for TextBlock
  sources/engine/Stride.UI/Controls/TextBlock.cs
  sources/engine/Stride.UI/Renderers/DefaultTextBlockRenderer.cs
Labels: area-UI
