Repository stride3d/stride, pull requests merged in 2024-05, with the labels that each got.

#2248 fix opentk link
  THIRD PARTY.md
Labels: area-Doc

#2247 fix: Use OperatingSystem.IsXyz instead of RuntimeInformation.IsOSPlatform
  deps/Stride.GitVersioning/Nerdbank.GitVersioning/GitExtensions.cs
  sources/assets/Stride.Core.Assets/PackageSessionPublicHelper.cs
  sources/core/Stride.Core/Platform.cs
Labels: area-Build

#2246 fix: Regression of new FBX importer on behalf of Noah
  sources/tools/Stride.Importer.3D/MeshConverter.cs
Labels: area-Asset

#2251 fix: Update Texture reload to prevent crash due to wrong type.
  sources/core/Stride.Core.Serialization/Serialization/Contents/ContentManager.cs
  sources/engine/Stride.Graphics/Data/TextureContentSerializer.cs
Labels: area-Graphics

#2254 GitHub docs improvements
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_update.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: area-Doc

#2264 README.md updates
  CODE_OF_CONDUCT.md
  README.md
Labels: area-Doc

#2250 fix: Adjust ToolLocator for all platforms
  sources/core/Stride.Core.Design/IO/UPath.cs
  sources/engine/Stride.Assets/Media/SoundAssetCompiler.cs
  sources/engine/Stride.Assets/Media/VideoAssetCompiler.cs
  sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontImporter.cs
  sources/engine/Stride.Assets/ToolLocator.cs
Labels: area-Build

#2277 fix: [Build] Rollback OperatingSystem.IsXYZ for net472 project
  deps/Stride.GitVersioning/Nerdbank.GitVersioning/GitExtensions.cs
Labels: area-Build

#2285 feat: New areas added
  .github/release.yml
Labels: area-Build

#2296 tests: Disable TestBlockingWindow, our Teamcity agent does not support it yet.
  sources/presentation/Stride.Core.Presentation.Tests/TestWindowsManager.cs
Labels: area-Graphics

#2215 fix: [Graphics] Fix light component API
  sources/engine/Stride.Rendering/Rendering/Lights/DirectLightBase.cs
  sources/engine/Stride.Rendering/Rendering/Lights/LightDirectional.cs
  sources/engine/Stride.Rendering/Rendering/Lights/LightPoint.cs
  sources/engine/Stride.Rendering/Rendering/Lights/LightSpot.cs
  sources/engine/Stride.Rendering/Rendering/Shadows/LightDirectionalShadowMapRenderer.cs
  sources/engine/Stride.Rendering/Rendering/Shadows/LightPointShadowMapRendererCubeMap.cs
  sources/engine/Stride.Rendering/Rendering/Shadows/LightPointShadowMapRendererParaboloid.cs
Labels: area-Graphics

#2297 test: Fix inconsistent FileVersion test
  sources/assets/Stride.Core.Assets.Tests/TestFileVersionManager.cs
  sources/assets/Stride.Core.Assets/FileVersionManager.cs
Labels: area-Build
