Repository stride3d/stride, pull requests merged in 2024-09, with the labels that each got.

#2419 fix: Xml comments fix 5
  sources/assets/Stride.Core.Assets/Bundle.cs
  sources/assets/Stride.Core.Assets/OverrideUpgraderHint.cs
  sources/core/Stride.Core.Mathematics/CollisionHelper.cs
  sources/core/Stride.Core.MicroThreading/MicroThread.cs
  sources/engine/Stride.Engine/Animations/AnimationCurve.cs
  sources/engine/Stride.Engine/Audio/AudioEmitterSoundController.cs
  sources/engine/Stride.Engine/Engine/AudioEmitterComponent.cs
  sources/engine/Stride.Engine/Engine/Design/EffectCompilationMode.cs
  sources/engine/Stride.Engine/Engine/Entity.cs
  sources/engine/Stride.Engine/Engine/EntityManager.cs
  sources/engine/Stride.Engine/Engine/InstancingUserBuffer.cs
  sources/engine/Stride.Engine/Profiling/GameProfilingSystem.cs
  sources/engine/Stride.Engine/Updater/ArrayUpdateResolver.cs
  sources/engine/Stride.Graphics/CommandList.cs
  sources/engine/Stride.Graphics/GraphicsDeviceExtensions.cs
  sources/engine/Stride.Rendering/Rendering/RenderContext.cs
Labels: area-Doc

#2423 docs: Enhance Entity class comment with detailed description.
  sources/engine/Stride.Engine/Engine/Entity.cs
Labels: area-Doc

#2435 fix: Restore LoadWICFile for Windows due to incomplete cross-platform functionality
  sources/tools/Stride.TextureConverter.Wrappers/DxtWrapper/dxt_wrapper.cpp
  sources/tools/Stride.TextureConverter/Backend/TexLibraries/DxtTexLib.cs
  sources/tools/Stride.TextureConverter/Backend/Wrappers/DxtNetWrapper.cs
Labels: area-Asset

#2436 docs: Added xml comment, and placed the namespace to correct position…
  sources/engine/Stride.Engine/Rendering/Compositing/GraphicsCompositor.cs
Labels: area-Doc

#2441 fix: extracting embedded texture files for materials from glTF file
  sources/tools/Stride.Importer.3D/Material/Materials.cs
  sources/tools/Stride.Importer.3D/MeshConverter.cs
Labels: area-Asset

#2458 fix: SpriteBatch rotation logic to original code
  sources/engine/Stride.Graphics/SpriteBatch.cs
Labels: area-Graphics

#2461 feat: [Math] - Exponential damping
  sources/core/Stride.Core.Mathematics/MathUtil.cs
  sources/engine/Stride.Rendering/Rendering/Utils/Math.sdsl
Labels: area-Math

#2402 feat: Assembly Processor Module Initializer to Roslyn
  deps/AssemblyProcessor/net8.0/Stride.Core.AssemblyProcessor.deps.json
  deps/AssemblyProcessor/net8.0/Stride.Core.AssemblyProcessor.dll
  deps/AssemblyProcessor/net8.0/Stride.Core.AssemblyProcessor.dll.hash
  deps/AssemblyProcessor/net8.0/Stride.Core.AssemblyProcessor.pdb
  deps/AssemblyProcessor/netstandard2.0/Stride.Core.AssemblyProcessor.deps.json
  deps/AssemblyProcessor/netstandard2.0/Stride.Core.AssemblyProcessor.dll
  deps/AssemblyProcessor/netstandard2.0/Stride.Core.AssemblyProcessor.dll.hash
  deps/AssemblyProcessor/netstandard2.0/Stride.Core.AssemblyProcessor.pdb
  sources/core/Stride.Core.AssemblyProcessor/AssemblyProcessorApp.cs
  sources/core/Stride.Core.AssemblyProcessor/AssemblyScanProcessor.cs
  sources/core/Stride.Core.AssemblyProcessor/AsyncBridgeProcessor.cs
  sources/core/Stride.Core.AssemblyProcessor/CecilExtensions.cs
  sources/core/Stride.Core.AssemblyProcessor/InitLocalsProcessor.cs
  sources/core/Stride.Core.AssemblyProcessor/ModuleInitializerProcessor.cs
  sources/core/Stride.Core.AssemblyProcessor/SerializationProcessor.cs
  sources/core/Stride.Core.AssemblyProcessor/UpdateEngineProcessor.cs
  sources/core/Stride.Core.CompilerServices/Common/WellKnownReferences.cs
  sources/core/Stride.Core.CompilerServices/Generators/ModuleInitializerGenerator.cs
  sources/core/Stride.Core.CompilerServices/Stride.Core.CompilerServices.csproj
  sources/engine/Stride.Shaders.Parser/Mixins/ShaderMixinCodeGen.cs
Labels: area-Build

#2463 chore: Build latest AssemblyProcessor changes
  deps/AssemblyProcessor/net8.0/Stride.Core.AssemblyProcessor.dll
  deps/AssemblyProcessor/net8.0/Stride.Core.AssemblyProcessor.dll.hash
  deps/AssemblyProcessor/net8.0/Stride.Core.AssemblyProcessor.pdb
  deps/AssemblyProcessor/netstandard2.0/Stride.Core.AssemblyProcessor.dll
  deps/AssemblyProcessor/netstandard2.0/Stride.Core.AssemblyProcessor.dll.hash
  deps/AssemblyProcessor/netstandard2.0/Stride.Core.AssemblyProcessor.pdb
Labels: area-Serialization
