Repository stride3d/stride, pull requests merged in 2025-01, with the labels that each got.

#2567 docs: Bepu, missing property summaries
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/CollidableComponent.cs
Labels: area-Physics

#2528 fix: UrlReference triggering quantum change propagation, leading to exceptions with cyclic scene references
  sources/assets/Stride.Core.Assets/Analysis/BuildAssetNode.cs
  sources/assets/Stride.Core.Assets/AssetRegistry.cs
  sources/assets/Stride.Core.Assets/Serializers/UrlReferenceSerializer.cs
  sources/core/Stride.Core.Design/TypeConverters/UrlReferenceConverter.cs
  sources/core/Stride.Core.Serialization/Serialization/Serializers/UrlReferenceDataSerializer.cs
  sources/core/Stride.Core.Serialization/Serialization/UrlReference.cs
  sources/core/Stride.Core.Serialization/Serialization/UrlReferenceBase.cs
  sources/core/Stride.Core.Serialization/Serialization/UrlReferenceHelper.cs
  sources/editor/Stride.Assets.Presentation/StrideDefaultAssetsPlugin.cs
  sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/AddNewItemCommand.cs
  sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Updaters/AbstractNodeEntryNodeUpdater.cs
  sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Updaters/SessionNodeUpdater.cs
  sources/editor/Stride.Core.Assets.Editor/Services/ContentReferenceHelper.cs
  sources/editor/Stride.Core.Assets.Editor/View/TemplateProviders/ContentReferenceTemplateProvider.cs
  sources/editor/Stride.Core.Assets.Editor/ViewModel/ContentReferenceViewModel.cs
Labels: area-Asset

#2577 docs: Update THIRD PARTY.md file
  THIRD PARTY.md
Labels: area-Build

#2525 fix: Empty GridLogViewer when messages are appended before the element is on screen
  sources/editor/Stride.Core.Assets.Editor/View/Controls/GridLogViewer.cs
Labels: area-GameStudio

#2512 feat: Port NuGetResolver.UI to AvaloniaUI
  sources/shared/Stride.NuGetResolver.UI/SplashScreenWindow.axaml
  sources/shared/Stride.NuGetResolver.UI/SplashScreenWindow.axaml.cs
  sources/shared/Stride.NuGetResolver.UI/SplashScreenWindow.xaml.cs
  sources/shared/Stride.NuGetResolver.UI/Stride.NuGetResolver.UI.csproj
  sources/shared/Stride.NuGetResolver/NuGetAssemblyResolver.cs
Labels: area-GameStudio
