Repository stride3d/stride, pull requests merged in 2025-02, with the labels that each got.

#2603 fix: bepu, removal of collidables while running a contact event leaves contact tracking in an unexpected state
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics.Tests/BepuTests.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics.Tests/Stride.BepuPhysics.Tests.csproj
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BepuSimulation.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/CollidableComponent.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Definitions/Contacts/ContactEventsManager.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Definitions/Contacts/IContactEventHandler.cs
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/StaticComponent.cs
Labels: area-Physics

#2627 docs: Contributor details updated
  .all-contributorsrc
  README.md
Labels: area-Doc

#2589 docs: XML Comments improvements
  sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
Labels: area-Doc

#2609 feat: Generalized per view resource binding
  sources/engine/Stride.Engine/Rendering/Compositing/ForwardRenderer.cs
  sources/engine/Stride.Rendering/Rendering/RootEffectRenderFeature.cs
  sources/engine/Stride.Rendering/Rendering/RootRenderFeature.cs
Labels: area-Graphics

#2632 fix: missing version update of Silk.NET to version 2.22.0
  sources/Directory.Packages.props
Labels: area-Build

#2598 fix: TextBlock enters an infinite loop if the given available space is too small to fit even one character.
  sources/engine/Stride.UI/Controls/TextBlock.cs
Labels: area-UI

#2629 fix: Add assets cleanup target when calling dotnet clean, clarify ref out of sync issues
  sources/assets/Stride.Core.Assets.CompilerApp/build/Stride.Core.Assets.CompilerApp.targets
  sources/core/Stride.Core/Serialization/ContentRefOutOfSyncException.cs
  sources/core/Stride.Core/Serialization/MemberSerializerCore.ttinclude
  sources/core/Stride.Core/Serialization/MemberSerializerGenerated.cs
Labels: area-Asset

#2606 feat: Add asset support for interface properties
  sources/assets/Stride.Core.Assets.Quantum/AssetPropertyGraph.cs
  sources/assets/Stride.Core.Assets/Analysis/BuildAssetNode.cs
  sources/assets/Stride.Core.Assets/Analysis/CollectionItemIdsAnalysis.cs
  sources/assets/Stride.Core.Assets/AssetRegistry.cs
  sources/assets/Stride.Core.Assets/CollectionIdGenerator.cs
  sources/assets/Stride.Core.Assets/Serializers/ContentReferenceSerializer.cs
  sources/editor/Stride.Assets.Presentation/AssetEditors/GameEditor/ViewModels/ContentReferenceCollector.cs
  sources/editor/Stride.Assets.Presentation/AssetEditors/GameEditor/ViewModels/GameEditorChangePropagator.cs
  sources/editor/Stride.Core.Assets.Editor/Components/FixAssetReferences/AssetReferenceReplacementViewModel.cs
  sources/editor/Stride.Core.Assets.Editor/Components/FixAssetReferences/FixAssetReferencesViewModel.cs
  sources/editor/Stride.Core.Assets.Editor/Components/FixReferences/FixReferencesViewModel.cs
  sources/editor/Stride.Core.Assets.Editor/Components/FixReferences/ReferenceReplacementViewModel.cs
  sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/AddNewItemCommand.cs
  sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/FetchAssetCommand.cs
  sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/PickupAssetCommand.cs
  sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/SetContentReferenceCommand.cs
  sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Updaters/AbstractNodeEntryNodeUpdater.cs
  sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Updaters/SessionNodeUpdater.cs
  sources/editor/Stride.Core.Assets.Editor/Quantum/ViewModels/AssetNodeViewModel.cs
  sources/editor/Stride.Core.Assets.Editor/Services/ContentReferenceHelper.cs
  sources/editor/Stride.Core.Assets.Editor/View/TemplateProviders/ContentReferenceTemplateProvider.cs
  sources/editor/Stride.Core.Assets.Editor/ViewModel/ContentReferenceViewModel.cs
  sources/editor/Stride.Editor/EditorGame/ContentLoader/LoaderReferenceManager.cs
  sources/engine/Stride.Assets/RuntimeTypesCollector.cs
  sources/engine/Stride.Debugger/Debugger/CloneReferenceSerializer.cs
Labels: area-Asset
